version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: tws_trading_db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: 'redis:5.0.5'
    command: ['redis-server', '--appendonly', 'yes']
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - redis-data:/data

  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build: .
    command: celery -A TwsTradingApp worker --loglevel=info -c 4
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A TwsTradingApp beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  redis-data:

