# Generated by Django 4.2.3 on 2023-07-14 14:34

import TwsTradingApp.trading.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3), TwsTradingApp.trading.models.validate_only_alphanumeric])),
                ('email', models.EmailField(max_length=254)),
                ('level', models.CharField(choices=[('Junior Trader', 'Junior Trader'), ('Senior Trader', 'Senior Trader')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameter1', models.IntegerField(blank=True, null=True)),
                ('parameter2', models.IntegerField(blank=True, null=True)),
                ('parameter3', models.IntegerField(blank=True, null=True)),
                ('strategy_description', models.TextField(blank=True, null=True)),
                ('parameters_description', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, choices=[('ES (E-mini S&P 500)', 'ES (E-mini S&P 500)'), ('NQ (E-mini Nasdaq 100)', 'NQ (E-mini Nasdaq 100)'), ('CL (Crude Oil)', 'CL (Crude Oil)'), ('NG (Natural Gas)', 'NG (Natural Gas)')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
            ],
            options={
                'unique_together': {('ticker', 'time')},
            },
        ),
        migrations.CreateModel(
            name='BacktestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('parameter_values', models.JSONField()),
                ('pnl_results', models.JSONField()),
                ('finish_time', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
        ),
    ]
