# Generated by Django 4.2.3 on 2023-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_portfolioinactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('parameter_values', models.JSONField()),
                ('results_id', models.IntegerField()),
                ('deployed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioInactive',
        ),
    ]
