# Generated by Django 4.2.3 on 2023-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_portfolio_delete_portfolioinactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
